image: node:latest

stages:
    - production
    - test
sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml


production:
    type: deploy
    stage: production
    script:
        - npm install -g heroku &>/dev/null
        - echo "machine api.heroku.com" > ~/.netrc
        - echo "  login $HEROKY_EMAIL" >> ~/.netrc
        - echo "  password $HEROKU_PASSWORD" >> ~/.netrc
        - echo "machine git.heroku.com" >> ~/.netrc
        - echo "  login $HEROKY_EMAIL" >> ~/.netrc
        - echo "  password $HEROKU_PASSWORD" >> ~/.netrc        
        - git config --global user.email "sinapsysunellez@gmail.com"
        - git config --global user.name "Sinapsys UNELLEZ"
        - git switch master
        - git status
        - heroku git:remote -a sinapsys-portal
        - git push -f heroku master 
    only:
        - master
